kind: pipeline
type: docker
name: build

steps:
  - name: Install PHP dependencies
    image: php:8.2-cli
    commands:
      - apt-get update && apt-get install -y unzip
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer update --no-interaction --prefer-dist --optimize-autoloader

  - name: Install Node dependencies
    image: node:18
    commands:
      - npm install

  - name: Build assets
    image: node:18
    commands:
      - npm run build

trigger:
  branch:
    - release/*
  event:
    exclude:
      - pull_request